name: Deploy AI App to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t bartsteer/ai-test-app .
        docker tag bartsteer/ai-test-app bartsteer/ai-test-app:latest
        docker push bartsteer/ai-test-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v1

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
